[deployment]
  region = "singapore"
  builder = "dockerfile"

[build]
  dockerfilePath = "Dockerfile"

[[services]]
  port = 8080
  healthCheckPath = "/auth/login"

  [services.environment]
    PORT = "8080"
    PROFILE = "default"
    ENABLE_SWAGGER = "false"
    JAVA_OPTS = "-Xmx256m"
